apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dnslm0uwg-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/dnslm0uwg-dotnet-basic